# Project
version=4.0.0
group=com.mrbysco.ghastcow

# Common
minecraft_version=1.20.5

# NeoForge
neo_version=20.5.14-beta

# Fabric
fabric_version=0.97.7+1.20.5
fabric_loader_version=0.15.10
cloth_config_version=14.0.126
mod_menu_version=10.0.0-beta.1

# Mod options
mod_name=GhastCow
mod_author=Mrbysco
mod_id=ghastcow

#Publishing
curseforge_id=483348
modrinth_id=XDDlmPmY

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false