modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/GhastCow/issues"
license="MIT"

[[mods]]
modId="ghastcow"
version="${file.jarVersion}"
displayName="The Ghast Cow mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-ghast-cow"
authors="Mrbysco"
description='''
Just a simple Ghast Cow boss
'''
[[dependencies.ghastcow]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.ghastcow]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"